services:
  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - JWT_SECRET=please-change
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  web:
    build: ./frontend
    command: ["npm","run","dev","--","--host","0.0.0.0"]
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
